apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gateway-db-pvc
  namespace: ticket-monitor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
